### ISSUE TITLE
License for the project.

### ISSUE THREAD

**Issue by yadavvi91** [MattDs17/SortingVisualizer#3]
There is no license mentioned in this project. Thus, as stated [here](http://stackoverflow.com/a/13669816), the code remains under copyright. It would be great if you added some permissive license like [Apache2](https://www.apache.org/licenses/LICENSE-2.0.txt), [MIT](https://opensource.org/licenses/MIT) or [GPL2](http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html) or [greater](http://www.gnu.org/licenses/gpl-3.0.en.html).

I want to continue this project further as and when time permits and would like to create an MVC
application to demonstrate sorting.

**Comment by DSouzaM** [comment]
I am glad you are interested in extending the project I've made! I have updated the licensing information (MIT) in the readme.
